language: android
dist: trusty

before_install:
  - wget https://services.gradle.org/distributions/gradle-6.6.1-bin.zip
  - unzip gradle-6.6.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.6.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - echo y | sdkmanager --update
  - echo y | sdkmanager "platform-tools"
  - echo y | sdkmanager "platforms;android-30"


script:
  - gradle lint
  - gradle assembleDebug

android:
  components:
    - platform-tools
    - tools
    - build-tools
    - android-30

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
